# Generated by Django 2.2 on 2019-04-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
